### PR TITLE
Add shooter, feeder, driver control, auto aim, and vision fixes

### LINKED ISSUE #11: Get auto-aiming working
- [x] read apriltag distance
- [x] figure out angle function based on distance from speaker
- [x] get auto-rotation (align to goal) working
- [ ] characterize shooter (figure out velocity vs motor output, etc.)
- [ ] shooting while moving (simple)
- [ ] shooting while moving (kinematic)
- [ ] shooting while moving (predictive)
- [ ] test **a lot** of times for consistency/reliability
- [ ] figure out percent chance of success on any given shot

### LINKED ISSUE #15: Arm code
Simple REV motion planning
Later: custom arm trajectories

### LINKED ISSUE #22: Accepting and Storing Note (Feeder)
The pizza box shooter needs to be able to accept the note from the intake or/and a person and load / hold the note until we are ready to shoot. 

- Need to find the proper PRM to hand note into the holding arm behind the shooter.
- Determine what position the motor will be in when loaded and waiting for note.

### LINKED ISSUE #29: Overrides
We need overrides for the second driver to use in emergencies. These will be controlled on shuffleboard. These include:
- [x] Disable field oriented control
- [x] Reset yaw value on pose estimator
- [x] Disable IMU (gyro)
- [x] Disable vision
- [x] Disable auto-aiming:
    - Resort to using the joystick
    - Shooter full power
- [x] Override all shooting presets

### LINKED ISSUE #30: Write commands
We have barely any commands written, though the subsystems are practically done. The commands that we need will be largely based on the current plan for button bindings, as seen [here](https://github.com/Brown-County-FIRST-Robotics/1716-2024-robot/blob/Controller_Input_Docs/docs/controller_layout.md), [this comment](https://github.com/Brown-County-FIRST-Robotics/1716-2024-robot/issues/30#issuecomment-1930886976) has a list of the needed commands.

### PR DESCRIPTION
**Pull request by cfinn68916**
Closes #11 
Closes #15
Closes #22
Closes #29
Closes #30

### CODE REVIEW

File: src/main/java/frc/robot/commands/SpeakerShoot.java [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+    controller = overrideController;
+    addRequirements(arm, shooter); // DO NOT add drive
+  }
+
+  @Override
+  public void initialize() {
+    shooter.setFiringBlocked(true);
+  }
+
+  public static double bestAng(double d, double z, double v) {
```
Comment (gldeA) [inline src/main/java/frc/robot/commands/SpeakerShoot.java:48]: JavaDocs here

File: src/main/java/frc/robot/commands/SpeakerShoot.java
Comment (gldeA) [inline src/main/java/frc/robot/commands/SpeakerShoot.java:1]: What is the difference between this and SimpleSpeakerShoot?

File: src/main/java/frc/robot/commands/TeleopDrive.java [hunk 2]
```diff
@@ -58,39 +53,31 @@ static boolean deadband(double x) {
     return Math.abs(x) < 0.1;
   }
 
+  static double deadscale(double x) {
+    return deadband(x) ? 0 : (x > 0 ? (x - 0.1) / 0.9 : (x + 0.1) / 0.9);
+  }
+
   @Override
   public void execute() {
```
Comment (gldeA) [inline src/main/java/frc/robot/commands/TeleopDrive.java:61]: add comments for what this is doing at each step

File: src/main/java/frc/robot/subsystems/shooter/Shooter.java [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+
+  public boolean isHolding() {
+    return holding;
+  }
+
+  public void setHolding(boolean holding) {
+    this.holding = holding;
+  }
+
+  boolean holding = false;
```
Comment (gldeA) [inline src/main/java/frc/robot/subsystems/shooter/Shooter.java:33]: Could you define member variables at the top of the class

File: src/main/java/frc/robot/subsystems/shooter/Shooter.java [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+
+  public void cmdVel(double v1, double v2) {
+    shooterIO.setVelocity(v1, v2);
+  }
+
+  public void cmdVoltage(double voltage) {
+    shooterIO.setVoltage(voltage);
+  }
+
+  public void commandSpeed(double exitVel) {
```
Comment (gldeA) [inline src/main/java/frc/robot/subsystems/shooter/Shooter.java:106]: Why is this a different naming scheme from `cmdVel` and `cmdVoltage`? (This is `commandSpeed`, not `cmdSpeed`)

File: src/main/java/frc/robot/subsystems/shooter/ShooterIOSparkFlexes.java [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+      pid1.setReference(vel1, CANSparkBase.ControlType.kVelocity, 0);
+      pid2.setReference(vel2, CANSparkBase.ControlType.kVelocity, 0);
+    } else {
+      motor1.set(0);
+      motor2.set(0);
+    }
+  }
+
+  @Override
+  public void smallStepTo(double pos1, double pos2) {
```
Comment (gldeA) [inline src/main/java/frc/robot/subsystems/shooter/ShooterIOSparkFlexes.java:99]: What is this method for?

File: src/main/java/frc/robot/subsystems/vision/Vision.java [hunk 6]
```diff
@@ -65,7 +66,9 @@ public void periodic() {
                             inputs[i].pose.get()[4],
                             inputs[i].pose.get()[5],
                             inputs[i].pose.get()[6]))
-                    .rotateBy(new Rotation3d(0, 0, Math.PI));
+                    .unaryMinus()
```
Comment (gldeA) [inline src/main/java/frc/robot/subsystems/vision/Vision.java:69]: can't you just rotate by `Rotation3d(0, 0, -Math.PI)` instead of using two `unaryMinus()`'s?

File: src/main/java/frc/robot/utils/ShootWhileMove.java
Comment (gldeA) [inline src/main/java/frc/robot/utils/ShootWhileMove.java:1]: JavaDoc

File: src/main/java/frc/robot/RobotContainer.java [hunk 7]
```diff
@@ -142,7 +163,73 @@ public void useAlliance() {
    * PS4} controllers or {@link edu.wpi.first.wpilibj2.command.button.CommandJoystick Flight
    * joysticks}.
    */
-  private void configureBindings() {}
+  private void configureBindings() {
```
Comment (gldeA) [inline src/main/java/frc/robot/RobotContainer.java:166]: More comments please

File: src/main/java/frc/robot/commands/SpeakerShoot.java
Comment (cfinn68916) [reply src/main/java/frc/robot/commands/SpeakerShoot.java:1]: SimpleSpeakerShoot doesn't do auto-aim

File: src/main/java/frc/robot/commands/Intake.java [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+public class Intake extends Command {
+  Shooter shooter;
+  Arm arm;
+  XboxController controller;
+  static LoggedTunableNumber armPreset = new LoggedTunableNumber("Presets/Intake_Arm", -0.14);
+  static LoggedTunableNumber topSpeed = new LoggedTunableNumber("Presets/Intake_Top", 1700);
+  static LoggedTunableNumber bottomSpeed = new LoggedTunableNumber("Presets/Intake_Bottom", -2000);
+  static LoggedTunableNumber armSourcePreset =
+      new LoggedTunableNumber("Presets/Intake_Arm_Source", 0.16); // TODO: find real preset
+  LoggedTunableNumber preset;
```
[the remark this answers is not in the document]
Comment (cfinn68916) [reply src/main/java/frc/robot/commands/Intake.java:24]: No, that's the kitbot angle, which will probably work.

File: src/main/java/frc/robot/subsystems/vision/Vision.java (hunk 6 above)
Comment (cfinn68916) [reply src/main/java/frc/robot/subsystems/vision/Vision.java:69]: I don't think so, 3D rotation isn't commutative nor associative.

**Review by gldeA — APPROVED** [review]
0/10,  rewrite in a better language
